<a href="https://colab.research.google.com/github/subClassy/Python-Tutorial_CMPT-466/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/aryanmikaeili/cmpt732_tutorials/blob/master/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CMPT 466

# Installing and importing numpy

To use numpy in our you should first install the module and then import it in our code. If you don't already have numpy, you can install it with __pip__ (type __pip install numpy__ in terminal).

In [ ]:
#importing numpy

import numpy as np

# Creating arrays

In [ ]:
#array of pre-defined values

a1 = np.array([1, 2, 3])
m1 = np.array([[1, 2, 3], [3,4, 5]], dtype = np.float64)

print('a1: ', a1, 'type:', a1.dtype)
print('m1: ', m1, 'type:', m1.dtype)

a1:  [1 2 3] type: int32
m1:  [[1. 2. 3.]
 [3. 4. 5.]] type: float64


In [ ]:
#array of all ones/zeros

a_zeros = np.zeros((3, 2))
a_ones = np.ones((3, 2))

print('a_zeros: ', a_zeros)
print('a_ones:', a_ones)

a_zeros:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
a_ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#shapes

a = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5],[4, 5, 6]])
print('shape of a:', a.shape)

shape of a: (4, 3)


In [ ]:
#transposing matrices and high-dimensional arrays

a = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5],[4, 5, 6]])
print('transpose of a:',a.T)
#can also use the function np.transpose
print('transpose of a (second method):', a.transpose(1, 0))

transpose of a: [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
transpose of a (second method): [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [ ]:
#indexing arrays

a = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5],[4, 5, 6]])

print(a[1])
print(a[1, 2])
print(a[1:3, 2])
print(a[:,::-1])
print(a[[1, 3], 2])
print(a < 3)

a[a < 3] = 10
print(a)

[2 3 4]
4
[4 5]
[[3 2 1]
 [4 3 2]
 [5 4 3]
 [6 5 4]]
[4 6]
[[ True  True False]
 [ True False False]
 [False False False]
 [False False False]]
[[10 10  3]
 [10  3  4]
 [ 3  4  5]
 [ 4  5  6]]


In [ ]:
#element-wise operations

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

#addition

print('a + b =', a + b)

#element-wise multiplication
print('ab =', a * b)

a + b = [3 5 7]
ab = [ 2  6 12]


In [ ]:
#broadcasting

a = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5]])
b= np.array([1, 2, 3])
print(a + b)

print(a + 3)

[[2 4 6]
 [3 5 7]
 [4 6 8]]
[[4 5 6]
 [5 6 7]
 [6 7 8]]


In [ ]:
#built-in mathematical operations

a= np.array([1, 4, 16])
print('sqrt of a:', np.sqrt(a))

a = np.array([0, np.pi / 2, np.pi / 4])
print('sin of a:', np.sin(a))

a = np.array([-2, -1, 0, 1, 2])
print('abolute value of a:', np.abs(a))

sqrt of a: [1. 2. 4.]
sin of a: [0.         1.         0.70710678]
abolute value of a: [2 1 0 1 2]


In [ ]:
#matrix multiplication

m1 = np.array([[1 ,2 ,3],[2, 3, 4]])
m2 = np.array([[1, 2],[2, 3],[3, 4]])

print('m1.m2 = ', np.matmul(m1, m2))
print('m1.m2 = ', m1 @ m2)
print('m1.m2 = ', np.dot(m1,m2))


m1.m2 =  [[14 20]
 [20 29]]
m1.m2 =  [[14 20]
 [20 29]]
m1.m2 =  [[14 20]
 [20 29]]


In [ ]:
m1 = np.array([[1, 2], [2, 3]])
m2 = np.array([[2, 3], [3, 4]])

print('m1 X m2 = ', np.cross(m1, m2))

m1 X m2 =  [-1 -1]


In [ ]:
m = np.diag([1, 2, 3])
print('inverse of m:', np.linalg.inv(m))

inverse of m: [[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
